/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/compressed-new.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Altair_Studio-Logo"].geometry}
        material={materials.M_Logo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Headphones.geometry}
        material={materials.M_Headphone}
        position={[20.22, 1.99, 4.03]}
        rotation={[1.55, 0.32, -0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DNA.geometry}
        material={materials.M_DNA}
        position={[19.9, -12.6, -17.01]}
        rotation={[1.26, 0.91, -1.86]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rocket003.geometry}
        material={materials.M_Rocket}
        position={[17.58, 25.26, -28.21]}
        rotation={[1.14, 0.81, 0.44]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curly.geometry}
        material={materials.M_Curly}
        position={[0.8, -15.96, 2.16]}
        rotation={[1.76, 0.07, -0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table.geometry}
        material={materials.M_Table}
        position={[0.59, -14.79, -27.84]}
        rotation={[0.98, 0.15, -1.24]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube001.geometry}
        material={materials.M_Roundcube}
        position={[-21.17, -4.1, -12.07]}
        rotation={[1.55, 0.05, 0.45]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Notebook.geometry}
        material={materials.M_Notebook}
        position={[-21.4, -14.96, -13.21]}
        rotation={[1.83, -0.23, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Zeppelin.geometry}
        material={materials.M_Zeppelin}
        position={[-23.64, -17.96, 17.51]}
        rotation={[2.72, -0.8, 2.71]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VR_Headset.geometry}
        material={materials.M_Headset}
        position={[6.92, -17.17, 27.59]}
        rotation={[1.29, 0.08, -0.64]}
        scale={5}
      />
    </group>
  );
}

useGLTF.preload("/compressed-new.glb");

