/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 music_hero.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/music_hero-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Altair_Studio-Logo'].geometry} material={materials.M_Logo} />
      <mesh geometry={nodes.Curly.geometry} material={materials.M_Curly} position={[-10.03, 20.45, -53.95]} rotation={[1.68, 0.17, 0.47]} scale={[0.97, 1.01, 1.52]} />
      <mesh geometry={nodes.Headphones.geometry} material={materials.M_Headphone} position={[20.22, 1.99, 4.03]} rotation={[1.55, 0.32, -0.76]} />
      <mesh geometry={nodes.Notebook.geometry} material={materials.M_Notebook} position={[-21.4, -14.96, -13.21]} rotation={[1.83, -0.23, 0.91]} />
      <mesh geometry={nodes.Rocket003.geometry} material={materials.M_Rocket} position={[17.58, 25.26, -28.21]} rotation={[1.14, 0.81, 0.44]} />
      <mesh geometry={nodes.VR_Headset.geometry} material={materials.M_Headset} position={[6.92, -17.17, 27.59]} rotation={[1.29, 0.08, -0.64]} scale={5} />
      <mesh geometry={nodes.Zeppelin.geometry} material={materials.M_Zeppelin} position={[-23.64, -17.96, 17.51]} rotation={[2.72, -0.8, 2.71]} scale={0} />
    </group>
  )
}

useGLTF.preload('/music_hero-transformed.glb')
