/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/SpotifyChickenDanceM.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from "react";

export function ChickenDanceM(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/SpotifyChickenDanceM.glb')
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []) 

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={1.531}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="tshirt001" geometry={nodes.tshirt001.geometry} material={materials.tshirt} skeleton={nodes.tshirt001.skeleton} />
          <skinnedMesh name="tshirt003" geometry={nodes.tshirt003.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt003.skeleton} />
          <skinnedMesh name="tshirt004" geometry={nodes.tshirt004.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt004.skeleton} />
          <skinnedMesh name="tshirt005" geometry={nodes.tshirt005.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt005.skeleton} />
          <skinnedMesh name="tshirt006" geometry={nodes.tshirt006.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt006.skeleton} />
          <skinnedMesh name="tshirt007" geometry={nodes.tshirt007.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt007.skeleton} />
          <skinnedMesh name="tshirt008" geometry={nodes.tshirt008.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt008.skeleton} />
          <group name="tshirt009">
            <skinnedMesh name="tshirt001mesh007" geometry={nodes.tshirt001mesh007.geometry} material={materials['Eye.001']} skeleton={nodes.tshirt001mesh007.skeleton} />
            <skinnedMesh name="tshirt001mesh007_1" geometry={nodes.tshirt001mesh007_1.geometry} material={materials['eye black.001']} skeleton={nodes.tshirt001mesh007_1.skeleton} />
            <skinnedMesh name="tshirt001mesh007_2" geometry={nodes.tshirt001mesh007_2.geometry} material={materials['eye pinnk.001']} skeleton={nodes.tshirt001mesh007_2.skeleton} />
          </group>
          <skinnedMesh name="tshirt011" geometry={nodes.tshirt011.geometry} material={materials.face} skeleton={nodes.tshirt011.skeleton} />
          <skinnedMesh name="tshirt012" geometry={nodes.tshirt012.geometry} material={materials.hands} skeleton={nodes.tshirt012.skeleton} />
          <skinnedMesh name="tshirt013" geometry={nodes.tshirt013.geometry} material={materials.hands} skeleton={nodes.tshirt013.skeleton} />
          <skinnedMesh name="tshirt014" geometry={nodes.tshirt014.geometry} material={materials.face} skeleton={nodes.tshirt014.skeleton} />
          <skinnedMesh name="tshirt015" geometry={nodes.tshirt015.geometry} material={materials.face} skeleton={nodes.tshirt015.skeleton} />
          <skinnedMesh name="tshirt016" geometry={nodes.tshirt016.geometry} material={nodes.tshirt016.material} skeleton={nodes.tshirt016.skeleton} />
          <skinnedMesh name="tshirt017" geometry={nodes.tshirt017.geometry} material={nodes.tshirt017.material} skeleton={nodes.tshirt017.skeleton} />
          <skinnedMesh name="tshirt018" geometry={nodes.tshirt018.geometry} material={materials.Material} skeleton={nodes.tshirt018.skeleton} />
          <skinnedMesh name="tshirt019" geometry={nodes.tshirt019.geometry} material={materials['ShoeLace left']} skeleton={nodes.tshirt019.skeleton} />
          <skinnedMesh name="tshirt020" geometry={nodes.tshirt020.geometry} material={materials.Shoes} skeleton={nodes.tshirt020.skeleton} />
          <skinnedMesh name="tshirt021" geometry={nodes.tshirt021.geometry} material={materials['Shoes feet']} skeleton={nodes.tshirt021.skeleton} />
          <skinnedMesh name="tshirt022" geometry={nodes.tshirt022.geometry} material={nodes.tshirt022.material} skeleton={nodes.tshirt022.skeleton} />
          <skinnedMesh name="tshirt024" geometry={nodes.tshirt024.geometry} material={materials['Shoes feet']} skeleton={nodes.tshirt024.skeleton} />
          <skinnedMesh name="tshirt025" geometry={nodes.tshirt025.geometry} material={nodes.tshirt025.material} skeleton={nodes.tshirt025.skeleton} />
          <skinnedMesh name="tshirt026" geometry={nodes.tshirt026.geometry} material={materials['Shoes feet']} skeleton={nodes.tshirt026.skeleton} />
          <skinnedMesh name="tshirt027" geometry={nodes.tshirt027.geometry} material={nodes.tshirt027.material} skeleton={nodes.tshirt027.skeleton} />
          <skinnedMesh name="tshirt029" geometry={nodes.tshirt029.geometry} material={nodes.tshirt029.material} skeleton={nodes.tshirt029.skeleton} />
          <skinnedMesh name="tshirt030" geometry={nodes.tshirt030.geometry} material={materials['ShoeLace left']} skeleton={nodes.tshirt030.skeleton} />
          <skinnedMesh name="tshirt031" geometry={nodes.tshirt031.geometry} material={materials['shirt black']} skeleton={nodes.tshirt031.skeleton} />
          <skinnedMesh name="tshirt032" geometry={nodes.tshirt032.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt032.skeleton} />
          <skinnedMesh name="tshirt033" geometry={nodes.tshirt033.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt033.skeleton} />
          <skinnedMesh name="tshirt034" geometry={nodes.tshirt034.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt034.skeleton} />
          <skinnedMesh name="tshirt035" geometry={nodes.tshirt035.geometry} material={nodes.tshirt035.material} skeleton={nodes.tshirt035.skeleton} />
          <skinnedMesh name="tshirt036" geometry={nodes.tshirt036.geometry} material={nodes.tshirt036.material} skeleton={nodes.tshirt036.skeleton} />
          <skinnedMesh name="tshirt037" geometry={nodes.tshirt037.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt037.skeleton} />
          <skinnedMesh name="tshirt038" geometry={nodes.tshirt038.geometry} material={nodes.tshirt038.material} skeleton={nodes.tshirt038.skeleton} />
          <skinnedMesh name="tshirt039" geometry={nodes.tshirt039.geometry} material={nodes.tshirt039.material} skeleton={nodes.tshirt039.skeleton} />
          <skinnedMesh name="tshirt040" geometry={nodes.tshirt040.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt040.skeleton} />
          <skinnedMesh name="tshirt041" geometry={nodes.tshirt041.geometry} material={nodes.tshirt041.material} skeleton={nodes.tshirt041.skeleton} />
          <skinnedMesh name="tshirt042" geometry={nodes.tshirt042.geometry} material={nodes.tshirt042.material} skeleton={nodes.tshirt042.skeleton} />
          <skinnedMesh name="tshirt043" geometry={nodes.tshirt043.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt043.skeleton} />
          <skinnedMesh name="tshirt044" geometry={nodes.tshirt044.geometry} material={nodes.tshirt044.material} skeleton={nodes.tshirt044.skeleton} />
          <skinnedMesh name="tshirt045" geometry={nodes.tshirt045.geometry} material={nodes.tshirt045.material} skeleton={nodes.tshirt045.skeleton} />
          <skinnedMesh name="tshirt046" geometry={nodes.tshirt046.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt046.skeleton} />
          <skinnedMesh name="tshirt047" geometry={nodes.tshirt047.geometry} material={nodes.tshirt047.material} skeleton={nodes.tshirt047.skeleton} />
          <skinnedMesh name="tshirt048" geometry={nodes.tshirt048.geometry} material={nodes.tshirt048.material} skeleton={nodes.tshirt048.skeleton} />
          <skinnedMesh name="tshirt049" geometry={nodes.tshirt049.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt049.skeleton} />
          <skinnedMesh name="tshirt050" geometry={nodes.tshirt050.geometry} material={nodes.tshirt050.material} skeleton={nodes.tshirt050.skeleton} />
          <skinnedMesh name="tshirt051" geometry={nodes.tshirt051.geometry} material={nodes.tshirt051.material} skeleton={nodes.tshirt051.skeleton} />
          <skinnedMesh name="tshirt052" geometry={nodes.tshirt052.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt052.skeleton} />
          <skinnedMesh name="tshirt053" geometry={nodes.tshirt053.geometry} material={nodes.tshirt053.material} skeleton={nodes.tshirt053.skeleton} />
          <skinnedMesh name="tshirt054" geometry={nodes.tshirt054.geometry} material={nodes.tshirt054.material} skeleton={nodes.tshirt054.skeleton} />
          <skinnedMesh name="tshirt055" geometry={nodes.tshirt055.geometry} material={materials['Hair Black.001']} skeleton={nodes.tshirt055.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SpotifyChickenDanceM.glb')
